[2024-10-28T11:08:14.559+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_binance_dag1.union_data_to_df manual__2024-10-28T11:02:34.468502+00:00 [queued]>
[2024-10-28T11:08:14.587+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_binance_dag1.union_data_to_df manual__2024-10-28T11:02:34.468502+00:00 [queued]>
[2024-10-28T11:08:14.588+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2024-10-28T11:08:14.629+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): union_data_to_df> on 2024-10-28 11:02:34.468502+00:00
[2024-10-28T11:08:14.642+0000] {standard_task_runner.py:57} INFO - Started process 306 to run task
[2024-10-28T11:08:14.649+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'api_binance_dag1', 'union_data_to_df', 'manual__2024-10-28T11:02:34.468502+00:00', '--job-id', '617', '--raw', '--subdir', 'DAGS_FOLDER/binance.Dag1.py', '--cfg-path', '/tmp/tmpztbvva73']
[2024-10-28T11:08:14.653+0000] {standard_task_runner.py:85} INFO - Job 617: Subtask union_data_to_df
[2024-10-28T11:08:14.686+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-10-28T11:08:14.781+0000] {task_command.py:410} INFO - Running <TaskInstance: api_binance_dag1.union_data_to_df manual__2024-10-28T11:02:34.468502+00:00 [running]> on host 3e776c2a96a1
[2024-10-28T11:08:15.094+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Danil' AIRFLOW_CTX_DAG_ID='api_binance_dag1' AIRFLOW_CTX_TASK_ID='union_data_to_df' AIRFLOW_CTX_EXECUTION_DATE='2024-10-28T11:02:34.468502+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-28T11:02:34.468502+00:00'
[2024-10-28T11:08:15.258+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/binance.Dag1.py", line 53, in push_from_xcom_to_df
    df[['Цена открытия','Наивысшая цена','Наименьшая цена','Цена последней совершенной сделки']] = df[['Цена открытия','Наивысшая цена','Наименьшая цена','Цена последней совершенной сделки']].round(2)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 3464, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1)[1]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1314, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1374, in _validate_read_indexer
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['Цена открытия', 'Наивысшая цена', 'Наименьшая цена',\n       'Цена последней совершенной сделки'],\n      dtype='object')] are in the [columns]"
[2024-10-28T11:08:15.308+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=api_binance_dag1, task_id=union_data_to_df, execution_date=20241028T110234, start_date=20241028T110814, end_date=20241028T110815
[2024-10-28T11:08:15.346+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 617 for task union_data_to_df ("None of [Index(['Цена открытия', 'Наивысшая цена', 'Наименьшая цена',\n       'Цена последней совершенной сделки'],\n      dtype='object')] are in the [columns]"; 306)
[2024-10-28T11:08:15.384+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-10-28T11:08:15.457+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
