[2024-10-28T10:50:00.344+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_binance_dag1.draw_smth_graphs manual__2024-10-28T10:43:45.885498+00:00 [queued]>
[2024-10-28T10:50:00.359+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_binance_dag1.draw_smth_graphs manual__2024-10-28T10:43:45.885498+00:00 [queued]>
[2024-10-28T10:50:00.360+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2024-10-28T10:50:00.401+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): draw_smth_graphs> on 2024-10-28 10:43:45.885498+00:00
[2024-10-28T10:50:00.410+0000] {standard_task_runner.py:57} INFO - Started process 238 to run task
[2024-10-28T10:50:00.414+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'api_binance_dag1', 'draw_smth_graphs', 'manual__2024-10-28T10:43:45.885498+00:00', '--job-id', '597', '--raw', '--subdir', 'DAGS_FOLDER/binance.Dag1.py', '--cfg-path', '/tmp/tmpeqr1m6ny']
[2024-10-28T10:50:00.417+0000] {standard_task_runner.py:85} INFO - Job 597: Subtask draw_smth_graphs
[2024-10-28T10:50:00.445+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-10-28T10:50:00.498+0000] {task_command.py:410} INFO - Running <TaskInstance: api_binance_dag1.draw_smth_graphs manual__2024-10-28T10:43:45.885498+00:00 [running]> on host 3e776c2a96a1
[2024-10-28T10:50:00.665+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Danil' AIRFLOW_CTX_DAG_ID='api_binance_dag1' AIRFLOW_CTX_TASK_ID='draw_smth_graphs' AIRFLOW_CTX_EXECUTION_DATE='2024-10-28T10:43:45.885498+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-28T10:43:45.885498+00:00'
[2024-10-28T10:50:00.705+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/binance.Dag1.py", line 70, in draw_graphs
    final_df['Дата открытия'] = final_df['Дата открытия'].dt.strftime('%d.%m.%Y') #не понимаю, почему эта колонка не передалась в датаформате из предыдущего таска
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/accessor.py", line 181, in __get__
    accessor_obj = self._accessor(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexes/accessors.py", line 506, in __new__
    raise AttributeError("Can only use .dt accessor with datetimelike values")
AttributeError: Can only use .dt accessor with datetimelike values
[2024-10-28T10:50:00.743+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=api_binance_dag1, task_id=draw_smth_graphs, execution_date=20241028T104345, start_date=20241028T105000, end_date=20241028T105000
[2024-10-28T10:50:00.766+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 597 for task draw_smth_graphs (Can only use .dt accessor with datetimelike values; 238)
[2024-10-28T10:50:00.788+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-10-28T10:50:00.823+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
