[2024-10-21T17:49:53.180+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_binance_dag1.draw_smth_graphs manual__2024-10-21T17:01:43.335906+00:00 [queued]>
[2024-10-21T17:49:53.213+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_binance_dag1.draw_smth_graphs manual__2024-10-21T17:01:43.335906+00:00 [queued]>
[2024-10-21T17:49:53.214+0000] {taskinstance.py:1308} INFO - Starting attempt 3 of 6
[2024-10-21T17:49:53.244+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): draw_smth_graphs> on 2024-10-21 17:01:43.335906+00:00
[2024-10-21T17:49:53.255+0000] {standard_task_runner.py:57} INFO - Started process 689 to run task
[2024-10-21T17:49:53.265+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'api_binance_dag1', 'draw_smth_graphs', 'manual__2024-10-21T17:01:43.335906+00:00', '--job-id', '467', '--raw', '--subdir', 'DAGS_FOLDER/binance.Dag1.py', '--cfg-path', '/tmp/tmp8b3pldui']
[2024-10-21T17:49:53.269+0000] {standard_task_runner.py:85} INFO - Job 467: Subtask draw_smth_graphs
[2024-10-21T17:49:53.296+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-10-21T17:49:53.366+0000] {task_command.py:410} INFO - Running <TaskInstance: api_binance_dag1.draw_smth_graphs manual__2024-10-21T17:01:43.335906+00:00 [running]> on host 3e776c2a96a1
[2024-10-21T17:49:53.570+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Danil' AIRFLOW_CTX_DAG_ID='api_binance_dag1' AIRFLOW_CTX_TASK_ID='draw_smth_graphs' AIRFLOW_CTX_EXECUTION_DATE='2024-10-21T17:01:43.335906+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-21T17:01:43.335906+00:00'
[2024-10-21T17:49:53.575+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/binance.Dag1.py", line 66, in draw_graphs
    json_data = ti.xcom_pull(key='endful_df', task_ids=union_data_to_df)
NameError: name 'union_data_to_df' is not defined
[2024-10-21T17:49:53.605+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=api_binance_dag1, task_id=draw_smth_graphs, execution_date=20241021T170143, start_date=20241021T174953, end_date=20241021T174953
[2024-10-21T17:49:53.635+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 467 for task draw_smth_graphs (name 'union_data_to_df' is not defined; 689)
[2024-10-21T17:49:53.682+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-10-21T17:49:53.736+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
