[2024-11-04T17:49:43.856+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2024-11-04T17:49:44.382+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_binance_dag1.1INCH scheduled__2024-11-02T09:00:00+00:00 [queued]>
[2024-11-04T17:49:44.456+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_binance_dag1.1INCH scheduled__2024-11-02T09:00:00+00:00 [queued]>
[2024-11-04T17:49:44.458+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2024-11-04T17:49:44.545+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): 1INCH> on 2024-11-02 09:00:00+00:00
[2024-11-04T17:49:44.579+0000] {standard_task_runner.py:57} INFO - Started process 74 to run task
[2024-11-04T17:49:44.597+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'api_binance_dag1', '1INCH', 'scheduled__2024-11-02T09:00:00+00:00', '--job-id', '990', '--raw', '--subdir', 'DAGS_FOLDER/binance.Dag1.py', '--cfg-path', '/tmp/tmpmy26wfc4']
[2024-11-04T17:49:44.610+0000] {standard_task_runner.py:85} INFO - Job 990: Subtask 1INCH
[2024-11-04T17:49:45.105+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-11-04T17:49:55.172+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 990 for task 1INCH ((psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8); 74)
[2024-11-04T17:50:02.714+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-11-04T17:50:02.836+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
